# This workflow uses version 2.0 of the workflow file format
version: 2.0

name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make build

labels:
  - my-label-1
  - my-label-2
